fsa

diff --git a/.github/workflows/reusable-workflow.yml b/.github/workflows/reusable-workflow.yml
--- a/.github/workflows/reusable-workflow.yml
+++ b/.github/workflows/reusable-workflow.yml
@@ -69,6 +69,12 @@ jobs:
         run: |
           echo "Running tests against environment: ${{ github.event.inputs.env }}"
           echo "envir=${{ inputs.env }}" >> $GITHUB_OUTPUT
+          status=(false) 
+          ||
+          { 
+            echo "Failed to get npm cache directory"
+            exit 1
+          }
 
   call-template-tests:
     if: ${{ !cancelled() && needs.dispatch.outputs.envir == '' }}
